### PR TITLE
trim unnecessary components

### LINKED ISSUE #37: Provide Trimmed-Down Images per Infrastructure and Kubernetes Version
**What would you like to be added**:
Today the images:
- are overly large (2x or 4x as large as the original first images; e.g. 200MB vs. 100MB for the plain toolbelt and 436MB vs. 116MB for the toolbelt with the `aws` CLI image)
- contain all infrastructures CLIs even though an operator needs usually only one (for a particular cluster)
- contains a 1.17 `kubectl`, which can be only used for clusters within the [skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl), so is mostly the wrong one for the currently supported Kubernetes versions in Gardener

**Why is this needed**:
The current images are too large, not specific enough (which adds to the first problem and results in longer startup times and 2-4x higher network usage and costs), and features an outdated `kubectl` that may fail/will be useless for clusters of a particular version.

**What do you suggest**:
Let's:
1. First understand why the images became so large and what we can do to cut them down and get them smaller again (fewer components, cleanup, different base OS if it's not too disruptive)
2. Build a matrix of images (infrastructure x `kubectl` version), so that a user and the dashboard can pick the right one (gardener/dashboard#842) and of course also the big one (for local usage)

### PR DESCRIPTION
**Pull request by jfortin-sap**
**What this PR does / why we need it**:
Trim unnecessary components to economize 170MB
**Which issue(s) this PR fixes**:
Partially addressing #37 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Trim unnecessary components to economize 170MB
```

### CODE REVIEW

**Comment by plkokanov** [comment]
Thanks for the PR. 
@jfortin-sap It seems that the krew tool and ketall also consume a lot of space. Perhaps we can make them optional since there is a command that lets you get all resources in a namspace - `kubectl api-resources --verbs=list --namespaced -o name \
  | xargs -n 1 kubectl get --show-kind --ignore-not-found -n <namespace>`

**Comment by jfortin-sap** [comment]
@plkokanov tested/updated. +170MB total savings now, up from 80MB

**Comment by plkokanov** [comment]
@jfortin-sap thanks

For future usage I would suggest to add a script to install krew similar to how it is done for [k9s](https://github.com/gardener/ops-toolbelt/blob/master/hacks/install_k9s), but I don't think we need it right now. @petersutter, @jfortin-sap  wdyt?

**Comment by petersutter** [comment]
yes a script would be nice to have, but I agree, we do not need it right away

**Review by plkokanov — APPROVED** [review]
/lgtm

**Review by petersutter — APPROVED** [review]
/lgtm

@jfortin-sap can you update the release notes, it still mentions the 80MB, which is outdated, right?

**Comment by jfortin-sap** [comment]
@petersutter Done

**Pull request merged**
