### PR TITLE
img per infra + updated client versions

### LINKED ISSUE #37: Provide Trimmed-Down Images per Infrastructure and Kubernetes Version
**What would you like to be added**:
Today the images:
- are overly large (2x or 4x as large as the original first images; e.g. 200MB vs. 100MB for the plain toolbelt and 436MB vs. 116MB for the toolbelt with the `aws` CLI image)
- contain all infrastructures CLIs even though an operator needs usually only one (for a particular cluster)
- contains a 1.17 `kubectl`, which can be only used for clusters within the [skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl), so is mostly the wrong one for the currently supported Kubernetes versions in Gardener

**Why is this needed**:
The current images are too large, not specific enough (which adds to the first problem and results in longer startup times and 2-4x higher network usage and costs), and features an outdated `kubectl` that may fail/will be useless for clusters of a particular version.

**What do you suggest**:
Let's:
1. First understand why the images became so large and what we can do to cut them down and get them smaller again (fewer components, cleanup, different base OS if it's not too disruptive)
2. Build a matrix of images (infrastructure x `kubectl` version), so that a user and the dashboard can pick the right one (gardener/dashboard#842) and of course also the big one (for local usage)

### PR DESCRIPTION
**Pull request by jfortin-sap**
**What this PR does / why we need it**:
Images per Infrastructure and updated client version for kubectl, gardenctl and aliyun

**Which issue(s) this PR fixes**:
Fixes #37 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Images per Infrastructure and updated client version for kubectl, gardenctl and aliyun
```

### CODE REVIEW

**Comment by vlerenc** [comment]
Awesome @jfortin-sap , thank you.

I noticed some CLIs have versions, some not. What's our strategy? Explicit versions are better, because you then have reproducible builds, but then someone needs to update the CLIs regularly. Maybe you/SRE could do so? Maybe only for the core components and the Gardener extensions teams for the CLIs?

Ah, the latest `kubectl` is `v1.20.4` and I believe it finally solves the problem with the managed fields, so we better get the version that has the fix for that in, please.

**Comment by jfortin-sap** [comment]
@vlerenc Can we merge? Updated kubctl version as requested, and created a separate task for explicit CLI versions https://github.com/gardener/ops-toolbelt/issues/44

**Comment by vlerenc** [comment]
Sure, whatever you think. I am not a reviewer here, so if you have tested it @jfortin-sap, please go ahead or ask your colleagues to review this PR.

**Review by tedteng — APPROVED** [review]

**Comment by jfortin-sap** [comment]
@plkokanov Do you approve?

**Review by neo-liang-sap — APPROVED** [review]

**Review by plkokanov — APPROVED** [review]
Sorry for the delay.
/lgtm

**Comment by plkokanov** [comment]
> I noticed some CLIs have versions, some not. What's our strategy? Explicit versions are better, because you then have reproducible builds, but then someone needs to update the CLIs regularly. Maybe you/SRE could do so? Maybe only for the core components and the Gardener extensions teams for the CLIs?

@vlerenc I also think It would become too much maintenance if all of the versions have to be constantly updated.

Currently only tools installed via curl and git support versioning, however It shouldn't be a problem to extend others (pip, apt and whatever comes in the future) to also support a version flag. Then we could specify versions for things like the azure cli, gcp cli, openstack and so on.

**Comment by vlerenc** [comment]
> I also think It would become too much maintenance if all of the versions have to be constantly updated.

Well, pinned versions are generally safer @plkokanov. How about doing that once every time we support a new Kubernetes version?

**Comment by plkokanov** [comment]
Makes sense, let me open a new issue to track this. We should also sync/update iaas cli versions with gardenctl versions.

**Pull request merged**
