### PR TITLE
add github action to receive auto update from gardenctl

### PR DESCRIPTION
**Pull request by neo-liang-sap**
**What this PR does / why we need it**:
when a new version of gardenctl is released, the gardenctl version in this repo is also updated automatically
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
when a new version of gardenctl is released, the gardenctl version in this repo is also updated automatically
```

### CODE REVIEW

**Comment by petersutter** [comment]
@neo-liang-sap have you checked with @AndreasBurger (see here https://github.com/gardener/gardenctl/issues/336#issuecomment-696882972)? What was the outcome and why isn't it possible to do this using https://gardener.github.io/cc-utils/traits/update_component_deps.html?

**Comment by neo-liang-sap** [comment]
Hi @petersutter , i sent one email to Andreas but didn't get response , i looked into https://gardener.github.io/cc-utils/traits/update_component_deps.html but didn't go into details...i had an internal discussion with @dansible as we are more familiar / more self control with github action so we decided to proceed with github action (like what we did between gardencl and homebrew-tap)
Thanks!
-Neo

**Comment by petersutter** [comment]
I pinged @AndreasBurger 

/hold until @AndreasBurger responds

**Pull request closed without merging**
