### PR TITLE
Adds ghelp, better welcome message pip for python3.6

### PR DESCRIPTION
**Pull request by plkokanov**
**What this PR does / why we need it**:
- Adds ghelp command which lists all tools which are specified and installed via the dockerfiles.
- Adds a better welcome message which mentions the ghelp command and a title `gardener shell`
- Adds pip3 so that python tools can be installed with it

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None

**Release note**:

```improvement operator
Added `ghelp` command and improved `welcome` message with a title
```
```improvement operator
Added python3.6 and pip3 so that python packages can be installed for the python3.6 interpreter.
```

### CODE REVIEW

**Comment by petersutter** [comment]
Screenshot 2020-01-22 at 13 23 04
 ghelp is really nice, I like it!

**Comment by petersutter** [comment]
Screenshot 2020-01-22 at 13 27 46
@plkokanov  got errors running `azure-cli` `google-cloud-sdk` or `aliyun-cli` using the gardenctl image, or did I make any mistake?

**Comment by plkokanov** [comment]
Hmm I'll have to fix the ghelp docs a bit (I currnetly retrieve the info directly from apt), for azure-cli and google-cloud-sdk the actual binaries are az and gcloud

**Comment by plkokanov** [comment]
Sort of fixed them. I can implement a better solution later on. Also changed the headers for the `ghelp` columns

image

**Comment by petersutter** [comment]
@plkokanov awscli also has to be fixed

**Comment by plkokanov** [comment]
Made it configurable so that the binaries can be specified for each package in the docker configuration files. Now if the `Notes` column doesn't mention that the tool/package is a library/package then the tool should be executable.

image

**Pull request merged**
