### PR TITLE
Adds vundle plugin manager

### PR DESCRIPTION
**Pull request by plkokanov**
**What this PR does / why we need it**:
Replaces the missing `pathogen` plugin manager for vim with `Vundle` and cleans up some plugins

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None

**Release note**:

```improvement operator
Vundle is now used as a plugin manager for vim
```

### CODE REVIEW

**Comment by plkokanov** [comment]
@msohn could you check if everything is ok with the licensing of the newly added plugins (under `dotfiles/.vim/bundle`)?

**Comment by petersutter** [comment]
@msohn ping

**Comment by msohn** [comment]
I checked the licenses of the added plugins:

VundleVim/Vundle.vim:
https://github.com/VundleVim/Vundle.vim/blob/master/LICENSE-MIT.txt
MIT license: that's ok

scrooloose/nerdtree
https://github.com/scrooloose/nerdtree/blob/master/LICENCE
DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
https://en.wikipedia.org/wiki/WTFPL
not an OSI approved license, needs to be checked

vim-syntastic/syntastic
https://github.com/vim-syntastic/syntastic/blob/master/LICENCE
DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
https://en.wikipedia.org/wiki/WTFPL
not an OSI approved license, needs to be checked

jistr/vim-nerdtree-tabs
https://github.com/jistr/vim-nerdtree-tabs/blob/master/LICENSE
Apache 2 license: that's ok

tpope/vim-sensible
https://github.com/tpope/vim-sensible#license
is licensed under the VIM license:
https://github.com/vim/vim/blob/master/runtime/doc/uganda.txt#L24
VIM license, needs to be checked

bronson/vim-trailing-whitespace
https://github.com/bronson/vim-trailing-whitespace
has no license: you can't use this as is, no license is equivalent to proprietary, ask the author to add a license or find another plugin

**Comment by plkokanov** [comment]
Thanks for the update, I'll resolve the plugins either tonight or tomorrow morning.

**Comment by plkokanov** [comment]
@msohn I checked the licenses:
WTFPL seems ok
```
Is the WTFPL a valid license?
Although the validity of the WTFPL has not been tested in courts, it is widely accepted as a valid license. Every major Linux distribution (Debian, Fedora, Arch, Gentoo, etc.) ships software licensed under the WTFPL, version 1 or 2. Bradley Kuhn (executive director of the Free Software Foundation) was quoted saying that the FSF’s folks agree the WTFPL is a valid free software license.
```
```
Can’t you change the wording? It’s inappropriate / childish / not corporate-compliant.
The WTFPL lets you relicense the work under any other license.
```

Vim license also seems ok. It is available directly inside the vim tool in the ops-toolbelt by executing: `:help license`

**Comment by msohn** [comment]
Ok, seems these licenses should be ok. The new repository will be scanned for license compatibility like all other repositories in the Gardener organisation. In case there are issues we'll get informed.

Though AFAICS https://github.com/bronson/vim-trailing-whitespace has no license.
We can't use code which has no license.

**Pull request merged**
